<?php

namespace Database\Seeders;

use App\Models\Tb_sinhvien;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        Tb_sinhvien::insert([
            'MaSinhVien'        => '191203366',
            'HoTen'             => 'Nguyễn Văn Sang',
            'NgaySinh'          => '2001-10-26',
            'NoiSinh'           => 'Hà Nội',
            'GioiTinh'          => 'Nam',
            'DanToc'            => 'Kinh',
            'TonGiao'           => 'Không',
            'QuocTich'          => 'Việt Nam',
            'SoCMTND'           => '123456436',
            'NgayCapCMTND'      => '2019-11-20',
            'NoiCapCMTND'       => 'CA Hà Nội',
            'DiaChiBaoTin'      => 'Hà Nội',
            'SDT'               => '0382963168',
            'Email'             => 'sangml@gmail.com',
            'HoKhauTinh'        => 'Hà Nội',
            'HoKhauHuyen'       => 'Đông Anh',
            'HoKhauXaPhuong'    => 'ABCD',
            'TinhTrangSinhVien' => 'Đang học',
            'HeDaoTao'          => 'Chính quy',
            'MaLop'             => '2',
            'NgayQuanLy' => '2019-09-10',
            'updated_date' => '2019-09-10',
            'NgayKetThuc'  => '2023-06-25',
        ]);
        Tb_sinhvien::insert([
            'MaSinhVien'        => '191204225',
            'HoTen'             => 'Nguyễn Nam',
            'NgaySinh'          => '2001-05-21',
            'NoiSinh'           => 'Thanh Hóa',
            'GioiTinh'          => 'Nam',
            'DanToc'            => 'Kinh',
            'TonGiao'           => 'Không',
            'QuocTich'          => 'Việt Nam',
            'SoCMTND'           => '123456436',
            'NgayCapCMTND'      => '2019-11-20',
            'NoiCapCMTND'       => 'CA Thanh Hóa',
            'DiaChiBaoTin'      => 'Vĩnh Lộc Thanh hóa',
            'SDT'               => '0382963168',
            'Email'             => 'nam@gmail.com',
            'HoKhauTinh'        => 'Thanh Hóa',
            'HoKhauHuyen'       => 'Vĩnh Lộc',
            'HoKhauXaPhuong'    => 'Vĩnh Quang',
            'TinhTrangSinhVien' => 'Đang học',
            'HeDaoTao'          => 'Chính quy',
            'MaLop'             => '3',
            'NgayQuanLy' => '2019-09-10',
            'updated_date' => '2019-09-10',
            'NgayKetThuc'  => '2023-06-25',
        ]);
        Tb_sinhvien::insert([
            'MaSinhVien'        => '191204226',
            'HoTen'             => 'Nguyễn Văn Hoàng',
            'NgaySinh'          => '2001-10-15',
            'NoiSinh'           => 'Hà Nội',
            'GioiTinh'          => 'Nam',
            'DanToc'            => 'Kinh',
            'TonGiao'           => 'Không',
            'QuocTich'          => 'Việt Nam',
            'SoCMTND'           => '123456436',
            'NgayCapCMTND'      => '2019-09-02',
            'NoiCapCMTND'       => 'CA Hà Nội',
            'DiaChiBaoTin'      => 'Hà Nội',
            'SDT'               => '0382963165',
            'Email'             => 'hoang@gmail.com',
            'HoKhauTinh'        => 'Hà Nội',
            'HoKhauHuyen'       => 'Cầu giấy',
            'HoKhauXaPhuong'    => 'Quan Hoa',
            'TinhTrangSinhVien' => 'Đã thôi học',
            'HeDaoTao'          => 'Chính quy',
            'MaLop'             => '1',
            'SoCMTND' => '191203368',
            'NgayCapCMTND' => '2022-10-10',
            'NoiCapCMTND' => "HaiHau",
            'NgayQuanLy' => '2019-09-10',
            'updated_date' => '2019-09-10',
            'NgayKetThuc'  => '2023-06-25',
        ]);
        Tb_sinhvien::insert([
            'MaSinhVien'        => '191204227',
            'HoTen'             => 'Phạm Thành',
            'NgaySinh'          => '2001-10-15',
            'NoiSinh'           => 'Hà Nội',
            'GioiTinh'          => 'Nam',
            'DanToc'            => 'Kinh',
            'TonGiao'           => 'Không',
            'QuocTich'          => 'Việt Nam',
            'SoCMTND'           => '123456436',
            'NgayCapCMTND'      => '2019-09-02',
            'NoiCapCMTND'       => 'CA Hà Nội',
            'DiaChiBaoTin'      => 'Hà Nội',
            'SDT'               => '0382963165',
            'Email'             => 'hoang@gmail.com',
            'HoKhauTinh'        => 'Hà Nội',
            'HoKhauHuyen'       => 'Cầu giấy',
            'HoKhauXaPhuong'    => 'Quan Hoa',
            'TinhTrangSinhVien' => 'Đã thôi học',
            'HeDaoTao'          => 'Chính quy',
            'MaLop'             => '1',
            'SoCMTND' => '191203368',
            'NgayCapCMTND' => '2022-10-10',
            'NoiCapCMTND' => "HaiHau",
            'NgayQuanLy' => '2019-09-10',
            'updated_date' => '2019-09-10',
            'NgayKetThuc'  => '2023-06-25',
        ]);
        Tb_sinhvien::insert([
            'MaSinhVien'        => '191204228',
            'HoTen'             => 'Nguyễn Hoàng Quân',
            'NgaySinh'          => '2001-10-15',
            'NoiSinh'           => 'Hà Nội',
            'GioiTinh'          => 'Nam',
            'DanToc'            => 'Kinh',
            'TonGiao'           => 'Không',
            'QuocTich'          => 'Việt Nam',
            'SoCMTND'           => '123456436',
            'NgayCapCMTND'      => '2019-09-02',
            'NoiCapCMTND'       => 'CA Hà Nội',
            'DiaChiBaoTin'      => 'Hà Nội',
            'SDT'               => '0382963165',
            'Email'             => 'hoang@gmail.com',
            'HoKhauTinh'        => 'Hà Nội',
            'HoKhauHuyen'       => 'Cầu giấy',
            'HoKhauXaPhuong'    => 'Quan Hoa',
            'TinhTrangSinhVien' => 'Đã tốt nghiệp',
            'HeDaoTao'          => 'Chính quy',
            'MaLop'             => '1',
            'SoCMTND' => '191203368',
            'NgayCapCMTND' => '2022-10-10',
            'NoiCapCMTND' => "HaiHau",
            'NgayQuanLy' => '2019-09-10',
            'updated_date' => '2019-09-10',
            'NgayKetThuc'  => '2023-06-25',
        ]);
        Tb_sinhvien::insert([
            'MaSinhVien'        => '191204229',
            'HoTen'             => 'Vũ Anh Quân',
            'NgaySinh'          => '2001-10-15',
            'NoiSinh'           => 'Hà Nội',
            'GioiTinh'          => 'Nam',
            'DanToc'            => 'Kinh',
            'TonGiao'           => 'Không',
            'QuocTich'          => 'Việt Nam',
            'SoCMTND'           => '123456436',
            'NgayCapCMTND'      => '2019-09-02',
            'NoiCapCMTND'       => 'CA Hà Nội',
            'DiaChiBaoTin'      => 'Hà Nội',
            'SDT'               => '0382963165',
            'Email'             => 'hoang@gmail.com',
            'HoKhauTinh'        => 'Hà Nội',
            'HoKhauHuyen'       => 'Cầu giấy',
            'HoKhauXaPhuong'    => 'Quan Hoa',
            'TinhTrangSinhVien' => 'Đã tốt nghiệp',
            'HeDaoTao'          => 'Chính quy',
            'MaLop'             => '1',
            'SoCMTND' => '191203368',
            'NgayCapCMTND' => '2022-10-10',
            'NoiCapCMTND' => "HaiHau",
            'NgayQuanLy' => '2019-09-10',
            'updated_date' => '2019-09-10',
            'NgayKetThuc'  => '2023-06-25',
        ]);
    }
}
